CREATE DATABASE AGENDAMENTO;
USE AGENDAMENTO;

CREATE TABLE PACIENTE{
IDPACIENTE PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(10) NOT NULL,
SEXO ENUM('F','M') NOT NULL,
EMAIL VARCHAR(20) NOT NULL UNIQUE,
NASCIMENTO DATE NOT NULL
};

CREATE TABLE MEDICO{
IDMEDICO PRIMARY KEY IDENTITY
NOME VARCHAR(10),
SEXO ENUM('F','M'),
ESPECIALIDADE VARCHAR(20),
ENFERMEIROS VARCHAR(20)
};

CREATE TABLE HOSPITAL{
IDHOSPITAL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(10),
BAIRRO VARCHAR(20),
RUA VARCHAR(20)
};

CREATE TABLE CONSULTA {
IDCONSULTA PRIMARY KEY AUTO_INCREMENT,
ID_PACIENTE INT,
ID_MEDICO INT,
ID_HOSPITAL INT,
DATA DATETIME VARCHAR(20),
DIAGNOSTICO VARCHAR(40)
};

CREATE TABLE INTERNAÇÃO{
IDINTERNAÇÃO PRIMARY KEY AUTO_INCREMENT,
QUARTO INT,
ENTRADA DATETIME
SAIDA DATETIME
OBSERVAÇÕES VARCHAR(20);
ID_CONSULTA INT UNIQUE
};

ALTER TABLE CONSULTA ADD CONSTRAINTS FK_PACIENTES
FOREIGN KEY (ID_PACIENTE) REFERENCES CONSULTA(IDCONSULTA);

ALTER TABLE CONSULTA ADD CONSTRAINTS FK_MEDICO
FOREIGN KEY (ID_MEDICO) REFERENCES CONSULTA(IDCONSULTA);

ALTER TABLE CONSULTA ADD CONSTRAINTS FK_HOSPITAL
FOREIGN KEY (ID_HOSPITAL) REFERENCES CONSULTA(IDCONSULTA);

ALTER TABLE INTERNAÇÃO ADD CONSTRAINTS FK_CONSULTAS
FOREIGN KEY (ID_CONSULTA) REFERENCES INTERNAÇÃO(IDINTERNAÇÃO);